version: "2.4"

services:
  bringup:
    image: "llabhishekll/llabhishekll-cp22:tortoisebot-ros2-bringup-real"
    networks:
      - default
    environment:
      - "ROS_DOMAIN_ID=0"
      - "RMW_IMPLEMENTATION=rmw_cyclonedds_cpp"
    volumes:
      - "/dev/input:/dev/input"
      - "/dev/video0:/dev/video0"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/gpiomem:/dev/gpiomem"
    device_cgroup_rules:
      - "c 13:* rmw"
      - "c 81:* rmw"
      - "c 188:* rmw"
      - "c 239:* rmw"
    ports:
      - "7400-65535:7400-65535"
    privileged: true
    tty: true

networks:
  default:
    driver: bridge