version: "2.4"

services:
  rviz:
    image: "llabhishekll/llabhishekll-cp22:tortoisebot-ros2-rviz-real"
    network_mode: "host"
    ipc: "host"
    environment:
      - "ROS_DOMAIN_ID=0"
      - "DISPLAY=:1"
      - "RMW_IMPLEMENTATION=rmw_cyclonedds_cpp"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    tty: true
