version: "2.4"

services:
  bringup:
    image: "llabhishekll/llabhishekll-cp22:tortoisebot-ros2-bringup-real"
    networks:
      - default
    environment:
      - "ROS_DOMAIN_ID=1"
      - "RMW_IMPLEMENTATION=rmw_cyclonedds_cpp"
    volumes:
      - "/dev/input:/dev/input"
      - "/dev/bus/usb:/dev/bus/usb"
      - "/dev/video0:/dev/video0"
      - "/dev/gpiomem:/dev/gpiomem"
    device_cgroup_rules:
      - "c 13:* rmw"
      - "c 189:* rmw"
      - "c 81:* rmw"
      - "c 160:* rmw"
    ports:
      - "7400-8000:7400-8000"
  rviz:
    image: "llabhishekll/llabhishekll-cp22:tortoisebot-ros2-rviz-real"
    networks:
      - default
    environment:
      - "ROS_DOMAIN_ID=1"
      - "DISPLAY=:1"
      - "RMW_IMPLEMENTATION=rmw_cyclonedds_cpp"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"

networks:
  default:
    driver: bridge
