version: "2.4"

services:
  roscore:
    image: "llabhishekll/llabhishekll-cp22:tortoisebot-ros1-roscore-real"
    network_mode: "host"
    ipc: "host"
    environment:
      - "ROS_HOSTNAME=master"
      - "ROS_MASTER_URI=http://master:11311"
      - "ROS_IPV6=on"
    ports:
      - "11311:11311"
    tty: true
  bringup:
    image: "llabhishekll/llabhishekll-cp22:tortoisebot-ros1-bringup-real"
    depends_on:
      - roscore
    network_mode: "host"
    ipc: "host"
    environment:
      - "ROS_HOSTNAME=master"
      - "ROS_MASTER_URI=http://master:11311"
      - "ROS_IPV6=on"
    volumes:
      - "/dev/input:/dev/input"
      - "/dev/video0:/dev/video0"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/gpiomem:/dev/gpiomem"
    device_cgroup_rules:
      - "c 13:* rmw"
      - "c 81:* rmw"
      - "c 188:* rmw"
      - "c 239:* rmw"
    privileged: true
    tty: true
  slam:
    image: "llabhishekll/llabhishekll-cp22:tortoisebot-ros1-slam-real"
    depends_on:
      - roscore
    network_mode: "host"
    ipc: "host"
    environment:
      - "ROS_HOSTNAME=master"
      - "ROS_MASTER_URI=http://master:11311"
      - "ROS_IPV6=on"
    tty: true
