version: "2.4"

services:
  roscore:
    image: "llabhishekll/llabhishekll-cp22:tortoisebot-ros1-roscore-real"
    networks:
      - default
    ports:
      - "11311:11311"
    tty: true
  bringup:
    image: "llabhishekll/llabhishekll-cp22:tortoisebot-ros1-bringup-real"
    depends_on:
      - roscore
    networks:
      - default
    environment:
      - "ROS_HOSTNAME=bringup"
      - "ROS_MASTER_URI=http://roscore:11311"
    volumes:
      - "/dev/input:/dev/input"
      - "/dev/video0:/dev/video0"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/gpiomem:/dev/gpiomem"
    device_cgroup_rules:
      - "c 13:* rmw"
      - "c 81:* rmw"
      - "c 188:* rmw"
      - "c 239:* rmw"
    tty: true
  slam:
    image: "llabhishekll/llabhishekll-cp22:tortoisebot-ros1-slam-real"
    depends_on:
      - roscore
    networks:
      - default
    environment:
      - "ROS_HOSTNAME=slam"
      - "ROS_MASTER_URI=http://roscore:11311"
    tty: true

networks:
  default:
    driver: bridge
