version: "2.4"

services:
  rviz:
    image: "llabhishekll/llabhishekll-cp22:tortoisebot-ros1-rviz-real"
    network_mode: "host"
    ipc: "host"
    environment:
      - "ROS_HOSTNAME=master"
      - "ROS_MASTER_URI=http://master:11311"
      - "ROS_IPV6=on"
      - "DISPLAY=:1"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
